<?php

/**
 * Implements hook_init().
 */
function views_fieldsets_init() {

}

/**
 * Implements hook_theme().
 */
function views_fieldsets_theme() {
	return array(
		'views_fieldsets_rearrange_form' => array(
			'render element' => 'form',
		),
	);
}

/**
 * Implements hook_form_alter().
 */
function views_fieldsets_form_alter($form, $form_state, $form_id) {
	drupal_set_message($form_id);
}

/**
 * Implements hook_form_FORM_ID_alter() for views_ui_rearrange_form().
 */
function views_fieldsets_form_views_ui_rearrange_form_alter($form, $form_state, $form_id = 'views_ui_rearrange_form') {
	foreach (element_children($form['fields']) as $field_name) {
		$form['fields'][$field_name]['hierarchy'] = array(
			'#type' => 'textfield',
			'#value' => 'nah',
		);
	}

	// Add javascript settings that will be added via $.extend for tabledragging
	$form['#js']['tableDrag']['arrange']['hierarchy'][0] = array(
		'target' => 'hierarchy',
		'source' => 'hierarchy',
		'relationship' => 'parent',
		'action' => 'match',
		'hidden' => FALSE,
		'limit' => 0,
	);

	$form['#theme'] = 'views_fieldsets_rearrange_form';

	print_r($form);
}

function theme_views_fieldsets_rearrange_form($variables) {
	$form = $variables['form'];
	return drupal_render_children($form);

	$rows = array();
	foreach (element_children($form['fields']) as $id) {
		if (isset($form['fields'][$id]['name'])) {
			$row = array();
			$row[] = drupal_render($form['fields'][$id]['name']) . drupal_render($form['fields'][$id]['hierarchy']);
			$form['fields'][$id]['weight']['#attributes']['class'] = array('weight');
			$row[] = drupal_render($form['fields'][$id]['weight']);
			$row[] = drupal_render($form['fields'][$id]['removed']) . l('<span>' . t('Remove') . '</span>', 'javascript:void()', array('attributes' => array('id' => 'views-remove-link-' . $id, 'class' => array('views-hidden', 'views-button-remove', 'views-remove-link'), 'alt' => t('Remove this item'), 'title' => t('Remove this item')), 'html' => TRUE));
			$rows[] = array(
				'data' => $row,
				'class' => array('draggable'),
				'id' => 'views-row-' . $id,
			);
		}
	}
	if (empty($rows)) {
		$rows[] = array(array(
			'data' => t('No fields available.'),
			'colspan' => '2',
		));
	}

	$header = array('', t('Weight'), t('Remove'));
	$output = drupal_render($form['override']);
	$output .= '<div class="scroll">';
	$output .= theme('table', array('header' => $header, 'rows' => $rows, 'attributes' => array('id' => 'arrange')));
	$output .= '</div>';
	$output .= drupal_render_children($form);
	drupal_add_tabledrag('arrange', 'order', 'sibling', 'weight');
	drupal_add_tabledrag('arrange', 'match', 'parent', 'hierarchy');

	return $output;
}

/**
 * Implements hook_form_FORM_ID_alter() for views_ui_edit_form().
 */
function views_fieldsets_form_views_ui_edit_form_alter($form, $form_state, $form_id = 'views_ui_edit_form') {
	drupal_add_js(drupal_get_path('module', 'views_fieldsets') . '/views_fieldsets.js');

//	$form['#attached']['js'][] = drupal_get_path('module', 'views_fieldsets') . '/views_fieldsets.js';
//	print_r($form['#attached']);
}

/**
 * Implements hook_views_api().
 */
function views_fieldsets_views_api() {
	return array(
		'version' => 3,
	);
}
