<?php

/**
 * Implements hook_init().
 */
function views_fieldsets_init() {

}

/**
 * Implements hook_theme().
 */
function views_fieldsets_theme() {
	return array(
		'views_fieldsets_rearrange_form' => array(
			'render element' => 'form',
		),
	);
}

/**
 * Implements hook_form_alter().
 */
function views_fieldsets_form_alter($form, $form_state, $form_id) {
	drupal_set_message($form_id);
}

/**
 * Implements hook_form_FORM_ID_alter() for views_ui_rearrange_form().
 */
function views_fieldsets_form_views_ui_rearrange_form_alter(&$form, &$form_state, $form_id = 'views_ui_rearrange_form') {
	if (!isset($form['fields']) || 'field' != end(explode('/', $form['#action']))) {
		return;
	}

	foreach (element_children($form['fields']) as $field_name) {
		$form['fields'][$field_name]['field_name'] = array(
			'#type' => 'hidden',
			'#value' => $field_name,
			'#attributes' => array('class' => array('field-name')),
		);
		$form['fields'][$field_name]['hierarchy'] = array(
			'#type' => 'hidden',
			'#default_value' => '',
			'#attributes' => array('class' => array('hierarchy')),
			'#size' => 5,
		);
		$form['fields'][$field_name]['depth'] = array(
			'#type' => 'hidden',
			'#default_value' => '',
			'#attributes' => array('class' => array('depth')),
			'#size' => 5,
		);

		$form['fields'][$field_name]['hierarchy']['#type'] = $form['fields'][$field_name]['depth']['#type'] = 'textfield';
	}

	$form['#theme'] = 'views_fieldsets_rearrange_form';

	array_unshift($form['buttons']['submit']['#submit'], 'views_fieldsets_rearrange_form_submit');

  dpm($form_state['view']);
}

/**
 * Submit handler for views_ui_rearrange_form().
 */
function views_fieldsets_rearrange_form_submit($form, &$form_state) {
	$values = &$form_state['values'];

  $display = &$form_state['view']->display[$form_state['display_id']];

  $fields = $display->handler->get_option('fields');

  $fieldsets = array();
  foreach ($fields as $field_name => $stuff) {
    $fieldsets[$field_name] = (string) @$values[$field_name]['hierarchy'];
  }

  $display->handler->set_option('fieldsets', $fieldsets);
}

/**
 * Theme function for views_fieldsets_rearrange_form.
 */
function theme_views_fieldsets_rearrange_form($variables) {
	$form = $variables['form'];

	$rows = array();
	foreach (element_children($form['fields']) as $id) {
		if (isset($form['fields'][$id]['name'])) {
			$row = array();
			$row[] = drupal_render($form['fields'][$id]['name']) .
				drupal_render($form['fields'][$id]['hierarchy']) .
				drupal_render($form['fields'][$id]['depth']) .
				drupal_render($form['fields'][$id]['field_name']);
			$form['fields'][$id]['weight']['#attributes']['class'] = array('weight');
			$row[] = drupal_render($form['fields'][$id]['weight']);
			$row[] = drupal_render($form['fields'][$id]['removed']) . l('<span>' . t('Remove') . '</span>', 'javascript:void()', array('attributes' => array('id' => 'views-remove-link-' . $id, 'class' => array('views-hidden', 'views-button-remove', 'views-remove-link'), 'alt' => t('Remove this item'), 'title' => t('Remove this item')), 'html' => TRUE));
			$rows[] = array(
				'data' => $row,
				'class' => array('draggable'),
				'id' => 'views-row-' . $id,
			);
		}
	}
	if (empty($rows)) {
		$rows[] = array(array(
			'data' => t('No fields available.'),
			'colspan' => '2',
		));
	}

	$header = array('', t('Weight'), t('Remove'));
	$output = drupal_render($form['override']);
	$output .= '<div class="scroll">';
	$output .= theme('table', array('header' => $header, 'rows' => $rows, 'attributes' => array('id' => 'arrange')));
	$output .= '</div>';
	$output .= drupal_render_children($form);

	drupal_add_tabledrag('arrange', 'match', 'parent', 'hierarchy', 'hierarchy', 'field-name', FALSE);
	drupal_add_tabledrag('arrange', 'depth', 'group', 'depth', NULL, NULL, FALSE);
	drupal_add_tabledrag('arrange', 'order', 'sibling', 'weight');

	return $output;
}

/**
 * Implements hook_form_FORM_ID_alter() for views_ui_edit_form().
 *
function views_fieldsets_form_views_ui_edit_form_alter($form, $form_state, $form_id = 'views_ui_edit_form') {
	drupal_add_js(drupal_get_path('module', 'views_fieldsets') . '/views_fieldsets.js');

//	$form['#attached']['js'][] = drupal_get_path('module', 'views_fieldsets') . '/views_fieldsets.js';
//	print_r($form['#attached']);
}

/**
 * Implements hook_views_api().
 */
function views_fieldsets_views_api() {
	return array(
		'version' => 3,
	);
}
